### ISSUE TITLE
Missing option on Program section

### ISSUE THREAD

**Issue by miton18** [haproxytech/config-parser#22]
There is missing options on `program` section.

- start-on-reload
- user
- group

https://cbonte.github.io/haproxy-dconv/2.1/configuration.html#3.7-option%20start-on-reload

```go
func getProgramParser() *Parsers {
	return createParsers([]ParserInterface{
		&simple.String{Name: "command"},
	})
}
```

**Comment by oktalz** [comment]
Hi @miton18,
PR has been merged. Thx.
