### ISSUE TITLE
Missing attributes not implemented

### ISSUE THREAD

**Issue by prometherion** [haproxytech/config-parser#25]
I was trying to dynamically set the following attributes

## global

- `server-state-file`
- `server-state-base`
- `hard-stop-after`
- `lua-load`
- `ssl-dh-param-file`
- `ssl-engine`
- `ssl-mode-async`
- `ssl-default-bind-ciphersuites`
- `ssl-default-server-ciphersuites`

## defaults

- `load-server-state-from-file`
- `options`
- `no option`

Tried as the following, YMMV

```go
var err error
err = p.Set(parser.Global, parser.GlobalSectionName, "server-state-file", &types.StringC{Value: "state-global"})
println(err)
// attribute not found
```

I'm getting the `attribute not found` error, even if I use the right parsers and section name according to each attribute.

Any plan to implement these attributes?

**Comment by oktalz** [comment]
hi @prometherion 
if they are missing we can add them to the roadmap

can you explain also in `defaults` sections what options are you using exactly?

**Comment by prometherion** [comment]
Thanks for the super quick answer! :rocket: 

I'd like to manipulate a snippet like the following:

```
defaults
    load-server-state-from-file global
    option {persist,dontlognull,http-server-close,http-keep-alive}
    no option http-use-htx
    timeout {client,client-fin,connect,http-keep-alive,http-request,queue,server,server-fin,tunnel}
```

Honestly, I was wondering to manage these attributes with a basic Go template and taking advantage of the HAProxy ability to load multiple configuration files.

**Comment by anitgandhi** [comment]
I ran into this for some other simple attributes, and was able to simplify customize the parser as such. Figured I'd share if it helps others.

```golang
func createParser() (*parser.Parser, error) {
	p := &parser.Parser{}

	// ...

	// Some of these are not implemented upstream,
	// so we can make a custom ones ourselves for now
	bufSize := &simple.Number{Name: "tune.bufsize"}
	bufSize.Init()

	maxRewrite := &simple.Number{Name: "tune.maxrewrite"}
	maxRewrite.Init()

	sslServerVerify := &simple.Word{Name: "ssl-server-verify"}
	sslServerVerify.Init()

	globals := p.Parsers[parser.Global][parser.GlobalSectionName]
	globals.Parsers = append(globals.Parsers, bufSize, maxRewrite, sslServerVerify)

	optionSpliceAuto := &simple.Option{Name: "splice-auto"}
	optionSpliceAuto.Init()
	defaults := p.Parsers[parser.Defaults][parser.DefaultSectionName]
	defaults.Parsers = append(defaults.Parsers, optionSpliceAuto)

	return p, nil
}
```
