### ISSUE TITLE
server-template in backend

### ISSUE THREAD

**Issue by tenminus11** [haproxytech/config-parser#28]
This works 
datar, err := p.Get(parser.Backends, bkname, "server")

I also needed to parse server-template
This doesn't works
datat, err := p.Get(parser.Backends, bkname, "server-template")

Also is there a way to get a All Section line in a formatted way 
So even if a attribute is not supported we can parse it ourself

**Comment by oktalz** [comment]
hi @tenminus11 
yes server-template does not have dedicated parser this can be added

this snippet gets all the lines that are not processed/have dedicated parsers
```Go
unprocessed, err = p.Get(parser.Backends, bkname, "")
if err == nil {
	for _, u := range unprocessed.([]types.UnProcessed) {
                fmt.Println(u.Value) 
        }
}
```

you can interact with this parser in a same way as with others (delete/add...)

**Comment by oktalz** [comment]
hi @tenminus11  server-template has been added as a parser
