### ISSUE TITLE
no parser force-persist and option allbackups

### ISSUE THREAD

**Issue by DeyunLuo** [haproxytech/config-parser#42]
hello,  very thanks for this project, I am a chinese user.
I don't find the [force-persist](http://cbonte.github.io/haproxy-dconv/2.5/configuration.html#4-force-persist) parser and   [option allbackups](http://cbonte.github.io/haproxy-dconv/2.5/configuration.html#4.2-option%20allbackups) in config-parser/v4/parsers/.
I write a [force-persist_generated.go ](https://github.com/DeyunLuo/config-parser/blob/master/parsers/force_persist.go)
can you support this ?

**Comment by oliwer** [comment]
Support for this keyword was added 2 years ago by @oktalz
