### ISSUE TITLE
can not parse implicit bind attr

### ISSUE THREAD

**Issue by revisegoal** [haproxytech/config-parser#53]
how to get *:5000 in this situation？
```cfg
frontend  main *:5000
    acl url_static       path_beg       -i /static /images /javascript /stylesheets
    acl url_static       path_end       -i .jpg .gif .png .css .js

    use_backend static          if url_static
    default_backend             app
```

**Comment by oktalz** [comment]
@revisegoal we don't plan to support that

that implicit behavior is not API friendly and has a clear and precise alternative with [bind](http://docs.haproxy.org/dev/configuration.html#bind%20(Alphabetically%20sorted%20keywords%20reference)) line
