### ISSUE TITLE
make program entry not fatal error

### ISSUE THREAD

**Issue by f1-outsourcing** [haproxytech/config-parser#6]
I am using haproxy container and to keep configuration file deployments simple. I would say one should just ignore this entry when haproxy is not started with -W
I am now using an environment variable to set the master worker mode.

```
[ALERT] 200/122357 (2214360) : Can't use a 'program' section without master worker mode.
[ALERT] 200/122357 (2214360) : Fatal errors found in configuration.
```

**Comment by oktalz** [comment]
Hi, @f1-outsourcing 

this does not seem to be related to config-parser.
as it looks by error messages you provided 
this is more related on how haproxy itself parses configuration.

**Comment by f1-outsourcing** [comment]
Can't you move these issues, recreating them is 2 - 3 times more work


-----Original Message-----
